# basic options
title:  Jekyll is awesome website
author:  mstwdusin
email:  mstwdustin@outlook.com 
description: A wonderful site
twitter_username:  non

# Build settings
markdown: kramdown
theme:  mininma
