# basic options
title:  Jekyll is awesome website
author:  mstwdusin
email:  mstwdustin@outlook.com 
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day
